### ISSUE TITLE
bug on generating extensions containers

### ISSUE THREAD

**Issue by betaglop** [libre-informatique/SymfonyLibrinfoCRMBundle#1]
Hi there,

I've got a problem generating the missing containers with the libre-informatique/crm-bundle... The commands fails really early for a "missing trait", which is one of the CRM containers.

The issue is within ```vendor/libre-informatique/crm-bundle/DependencyInjection/Compiler/NormalizerCompilerPass.php``` in the ```class_exists()``` call. It might be ```class_exists($class, false)``` to avoid calling the autoload process... and require the traits too early.

This will happen in every bundle using ```CompilerPass```es within their initialization.

So the patch would be:
```php
diff --git a/DependencyInjection/Compiler/NormalizerCompilerPass.php b/DependencyInjection/Compiler/NormalizerCompilerPass.php
index e30c3f6..9772d3a 100644
--- a/DependencyInjection/Compiler/NormalizerCompilerPass.php
+++ b/DependencyInjection/Compiler/NormalizerCompilerPass.php
@@ -11,13 +11,15 @@ class NormalizerCompilerPass implements CompilerPassInterface
     {
         $service = $container->getDefinition('librinfo.base_entities.listener.normalize');
         $config = $container->getParameter('librinfo_crm');
-        foreach ($config as $class => $settings) {
+        foreach ($config as $class => $settings)
+        {
             $class = "Librinfo\\CRMBundle\\Entity\\" . $class;
-            if ( class_exists($class) && !empty($settings['normalize']) ) {
+            if ( class_exists($class, false) && !empty($settings['normalize']) )
+            {
                 $arg = [$class => $settings['normalize']];
                 $service->addMethodCall('addActions', [$arg]);
             }
         }
 
     }
-}
\ No newline at end of file
+}
```

Please consider this...

**Comment by marcoslibre** [comment]
[b27b9992d6b45](https://github.com/libre-informatique/SymfonyLibrinfoCRMBundle/commit/b27b9992d6b4547cae375a320e1eba8b112ad8c8) fixes the issue.
Thanks
